#!/usr/bin/env bash
set -Eeuo pipefail

umask 077

readonly GOVERNANCE_ROOT="/opt/propertyquarry-security/governance"
readonly EXPECTED_FILE="${GOVERNANCE_ROOT}/expected.env"
readonly EVIDENCE_ROOT="/opt/propertyquarry-security/evidence"

fail() {
  printf 'PropertyQuarry security runner preflight denied: %s\n' "$1" >&2
  exit 1
}

[[ "$(id -un)" == "pqsecurity" ]] || fail "unexpected execution user"
[[ -f "${EXPECTED_FILE}" ]] || fail "root-owned expectation file is missing"
[[ "$(stat -c '%U:%G:%a' "${EXPECTED_FILE}")" == "root:root:444" ]] \
  || fail "expectation file ownership or mode changed"

# The file is generated by the reviewed bootstrap and is only sourced after its
# root ownership and non-writability have been proven.
# shellcheck disable=SC1090
source "${EXPECTED_FILE}"

[[ "$(sha256sum "$0" | awk '{print $1}')" == "${EXPECTED_PREFLIGHT_SHA256}" ]] \
  || fail "preflight hook identity changed"
[[ "$(stat -c '%U:%G:%a' "$0")" == "root:root:555" ]] \
  || fail "preflight hook ownership or mode changed"

[[ "${GITHUB_REPOSITORY:-}" == "${EXPECTED_REPOSITORY}" ]] || fail "repository mismatch"
[[ "${GITHUB_EVENT_NAME:-}" == "workflow_dispatch" ]] || fail "event mismatch"
[[ "${GITHUB_WORKFLOW_REF:-}" == "${EXPECTED_WORKFLOW_REF}" ]] || fail "workflow ref mismatch"
[[ "${GITHUB_WORKFLOW_SHA:-}" == "${EXPECTED_HEAD_SHA}" ]] || fail "workflow SHA mismatch"
[[ "${GITHUB_JOB:-}" == "propertyquarry-flagship-security" ]] || fail "job mismatch"
[[ "${GITHUB_RUN_ID:-}" == "${EXPECTED_RUN_ID}" ]] || fail "run id mismatch"
[[ "${GITHUB_RUN_ATTEMPT:-}" == "${EXPECTED_RUN_ATTEMPT}" ]] || fail "run attempt mismatch"
[[ "${GITHUB_SHA:-}" == "${EXPECTED_HEAD_SHA}" ]] || fail "head SHA mismatch"
[[ "${GITHUB_REF:-}" == "refs/heads/main" ]] || fail "ref mismatch"
[[ "${PROPERTYQUARRY_WORKFLOW_HEAD_SHA:-}" == "${EXPECTED_HEAD_SHA}" ]] \
  || fail "security workflow binding mismatch"
[[ "${PROPERTYQUARRY_SECURITY_RUNNER_LABEL:-}" == "${EXPECTED_RUNNER_LABEL}" ]] \
  || fail "one-time runner label mismatch"
[[ "${PROPERTYQUARRY_WEB_IMAGE:-}" == "${EXPECTED_WEB_IMAGE}" ]] || fail "web image mismatch"
[[ "${PROPERTYQUARRY_RENDER_IMAGE:-}" == "${EXPECTED_RENDER_IMAGE}" ]] \
  || fail "render image mismatch"
[[ "${RUNNER_NAME:-}" == "${EXPECTED_RUNNER_NAME}" ]] || fail "runner name mismatch"
[[ "${RUNNER_OS:-}" == "Linux" ]] || fail "runner operating system mismatch"
[[ "${RUNNER_ARCH:-}" == "X64" ]] || fail "runner architecture mismatch"
[[ "${ACTIONS_RUNNER_HOOK_JOB_STARTED:-}" == "$0" ]] || fail "start-hook binding mismatch"
[[ "${DOCKER_HOST:-}" == "${EXPECTED_DOCKER_HOST}" ]] || fail "Docker socket binding mismatch"
[[ "${TRIVY_CACHE_DIR:-}" == "${EXPECTED_TRIVY_CACHE_DIR}" ]] || fail "Trivy cache binding mismatch"
[[ "${TRIVY_CACHE_BACKEND:-}" == "memory" ]] || fail "Trivy cache backend is not memory-only"

for secret_name in GH_TOKEN GITHUB_TOKEN PROPERTYQUARRY_SECURITY_RUNNER_TOKEN PQ_RUNNER_TOKEN PQ_RUNNER_TOKEN_EXPIRES_AT; do
  [[ -z "${!secret_name+x}" ]] || fail "bootstrap credential leaked into the inner runner"
done

[[ "$(id -nG)" == "pqsecurity" ]] || fail "unexpected supplementary group"
if sudo -n true >/dev/null 2>&1; then
  fail "pqsecurity unexpectedly has sudo authority"
fi
if [[ -r /var/run/docker.sock || -w /var/run/docker.sock ]]; then
  fail "pqsecurity can access the outer Docker socket"
fi

verify_file() {
  local path="$1"
  local expected_sha="$2"
  local expected_mode="$3"
  [[ -f "${path}" ]] || fail "required governed file is missing"
  [[ "$(sha256sum "${path}" | awk '{print $1}')" == "${expected_sha}" ]] \
    || fail "governed file hash changed"
  [[ "$(stat -c '%U:%G:%a' "${path}")" == "${expected_mode}" ]] \
    || fail "governed file ownership or mode changed"
}

verify_file "${EXPECTED_PIP_AUDIT_BIN}" "${EXPECTED_PIP_AUDIT_SHA256}" "root:root:755"
verify_file "${EXPECTED_PYTHON_BIN}" "${EXPECTED_PYTHON_SHA256}" "root:root:755"
verify_file "${EXPECTED_SYFT_BIN}" "${EXPECTED_SYFT_SHA256}" "root:root:555"
verify_file "${EXPECTED_TRIVY_BIN}" "${EXPECTED_TRIVY_SHA256}" "root:root:555"
verify_file "${EXPECTED_DOCKER_BIN}" "${EXPECTED_DOCKER_SHA256}" "root:root:755"
verify_file "${EXPECTED_DOCKERD_BIN}" "${EXPECTED_DOCKERD_SHA256}" "root:root:755"
verify_file "${EXPECTED_CONTAINERD_BIN}" "${EXPECTED_CONTAINERD_SHA256}" "root:root:755"
verify_file "${EXPECTED_RUNC_BIN}" "${EXPECTED_RUNC_SHA256}" "root:root:755"
verify_file "${EXPECTED_ROOTLESSKIT_BIN}" "${EXPECTED_ROOTLESSKIT_SHA256}" "root:root:755"
verify_file "${EXPECTED_SLIRP_BIN}" "${EXPECTED_SLIRP_SHA256}" "root:root:755"
verify_file "${EXPECTED_NEWUIDMAP_BIN}" "${EXPECTED_NEWUIDMAP_SHA256}" "root:root:4755"
verify_file "${EXPECTED_NEWGIDMAP_BIN}" "${EXPECTED_NEWGIDMAP_SHA256}" "root:root:4755"
verify_file "${EXPECTED_APPARMOR_PROFILE}" "${EXPECTED_APPARMOR_PROFILE_SHA256}" "root:root:644"
verify_file "${EXPECTED_RUNNER_LISTENER}" "${EXPECTED_RUNNER_LISTENER_SHA256}" "root:root:555"
verify_file "${EXPECTED_RUNNER_ENV}" "${EXPECTED_RUNNER_ENV_SHA256}" "root:root:444"
verify_file "${EXPECTED_RUNNER_PATH}" "${EXPECTED_RUNNER_PATH_SHA256}" "root:root:444"
verify_file "${EXPECTED_RUNNER_LOCK}" "${EXPECTED_RUNNER_LOCK_SHA256}" "root:root:444"

[[ "$("${EXPECTED_PIP_AUDIT_BIN}" --version)" == "pip-audit 2.10.1" ]] \
  || fail "pip-audit version changed"
[[ "$("${EXPECTED_PYTHON_BIN}" -c 'import importlib.metadata, platform; print(platform.python_version() + "|" + importlib.metadata.version("pip-audit"))')" == "3.12.13|2.10.1" ]] \
  || fail "scanner Python environment changed"
[[ "$(sysctl -n kernel.apparmor_restrict_unprivileged_userns)" == "1" ]] \
  || fail "Ubuntu user-namespace restriction changed"

verify_file "${EXPECTED_TRIVY_CACHE_DIR}/db/trivy.db" "${EXPECTED_TRIVY_DB_SHA256}" "root:root:444"
verify_file "${EXPECTED_TRIVY_CACHE_DIR}/db/metadata.json" "${EXPECTED_TRIVY_DB_METADATA_SHA256}" "root:root:444"
verify_file "${EXPECTED_TRIVY_CACHE_DIR}/java-db/trivy-java.db" "${EXPECTED_TRIVY_JAVA_DB_SHA256}" "root:root:444"
verify_file "${EXPECTED_TRIVY_CACHE_DIR}/java-db/metadata.json" "${EXPECTED_TRIVY_JAVA_METADATA_SHA256}" "root:root:444"
[[ "$(stat -c '%U:%G:%a' "${EXPECTED_TRIVY_CACHE_DIR}")" == "root:root:555" ]] \
  || fail "Trivy snapshot root ownership or mode changed"

verify_fresh_metadata() {
  local metadata="$1"
  local maximum_update_age="$2"
  local require_unexpired="$3"
  local now_epoch updated_epoch next_epoch downloaded_epoch
  now_epoch="$(date -u +%s)"
  updated_epoch="$(date -u -d "$(jq -er '.UpdatedAt' "${metadata}")" +%s)" \
    || fail "invalid Trivy database update timestamp"
  next_epoch="$(date -u -d "$(jq -er '.NextUpdate' "${metadata}")" +%s)" \
    || fail "invalid Trivy database expiry timestamp"
  downloaded_epoch="$(date -u -d "$(jq -er '.DownloadedAt' "${metadata}")" +%s)" \
    || fail "invalid Trivy database download timestamp"
  (( updated_epoch <= now_epoch )) || fail "Trivy database update timestamp is in the future"
  (( now_epoch - updated_epoch <= maximum_update_age )) || fail "Trivy database snapshot is stale"
  (( downloaded_epoch <= now_epoch && now_epoch - downloaded_epoch <= 21600 )) \
    || fail "Trivy database snapshot was not freshly staged"
  if [[ "${require_unexpired}" == "true" ]]; then
    (( next_epoch > now_epoch )) || fail "Trivy vulnerability database snapshot has expired"
  else
    (( next_epoch > updated_epoch )) || fail "Trivy Java database cadence is malformed"
  fi
}

verify_fresh_metadata "${EXPECTED_TRIVY_CACHE_DIR}/db/metadata.json" 172800 true
verify_fresh_metadata "${EXPECTED_TRIVY_CACHE_DIR}/java-db/metadata.json" 604800 false

[[ -S "${EXPECTED_DOCKER_SOCKET}" ]] || fail "rootless Docker socket is missing"
[[ ! -L "${EXPECTED_DOCKER_SOCKET}" ]] || fail "rootless Docker socket is a symlink"
[[ "$(stat -Lc '%U:%G' "${EXPECTED_DOCKER_SOCKET}")" == "pqsecurity:pqsecurity" ]] \
  || fail "rootless Docker socket ownership changed"
case "$(stat -Lc '%a' "${EXPECTED_DOCKER_SOCKET}")" in
  600|660) ;;
  *) fail "rootless Docker socket mode changed" ;;
esac

docker_info="$(docker info --format '{{json .}}')" || fail "rootless Docker daemon is unavailable"
jq -e --arg root "${EXPECTED_DOCKER_ROOT}" '
  .ServerVersion == "28.0.4" and
  .Driver == "overlay2" and
  .CgroupDriver == "systemd" and
  (.SecurityOptions | any(contains("name=rootless"))) and
  .DockerRootDir == $root
' <<<"${docker_info}" >/dev/null || fail "rootless Docker daemon posture changed"
[[ -z "$(docker ps --all --quiet)" ]] || fail "unexpected container exists on the scan daemon"

verify_image() {
  local image="$1"
  local found=""
  local digest
  while IFS= read -r digest; do
    if [[ "${digest}" == "${image}" ]]; then
      found="yes"
    fi
  done < <(docker image inspect "${image}" --format '{{range .RepoDigests}}{{println .}}{{end}}')
  [[ "${found}" == "yes" ]] || fail "exact image digest is not local"
  [[ "$(docker image inspect "${image}" --format '{{.Os}}/{{.Architecture}}')" == "linux/amd64" ]] \
    || fail "image platform mismatch"
}

verify_image "${EXPECTED_WEB_IMAGE}"
verify_image "${EXPECTED_RENDER_IMAGE}"

mkdir -p "${EVIDENCE_ROOT}"
jq -n \
  --arg schema "propertyquarry.security_runner_preflight.v1" \
  --arg status "pass" \
  --arg repository "${GITHUB_REPOSITORY}" \
  --arg run_id "${GITHUB_RUN_ID}" \
  --arg run_attempt "${GITHUB_RUN_ATTEMPT}" \
  --arg head_sha "${GITHUB_SHA}" \
  --arg runner_name "${RUNNER_NAME}" \
  --arg checked_at "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
  '{schema:$schema,status:$status,repository:$repository,run_id:$run_id,run_attempt:$run_attempt,head_sha:$head_sha,runner_name:$runner_name,checked_at:$checked_at}' \
  >"${EVIDENCE_ROOT}/preflight-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}.json"
chmod 600 "${EVIDENCE_ROOT}/preflight-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}.json"

printf 'PropertyQuarry security runner preflight passed for run %s attempt %s.\n' \
  "${GITHUB_RUN_ID}" "${GITHUB_RUN_ATTEMPT}"
